# Generated by Django 2.0.6 on 2018-07-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nameapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='desc',
            new_name='Comment',
        ),
    ]
